language: csharp
#mono: none
dotnet: 2.0.0
solution: LuxaforLyncTool/LuxaforLyncTool.sln
script:
  - cd LuxaforLyncTool
  - dotnet restore
  - cd LuxaforLyncTool_Light
  - dotnet build LuxaforLyncTool_Light.csproj -c Release
  - cd ..
  - cd LuxaforLyncTool_Lync
  - dotnet build LuxaforLyncTool_Lync.csproj -c Release
  - cd ..
  - cd LuxaforLyncTool_Client
  - xbuild LuxaforLyncTool_Client /p:Configuration=Release
