jobs:
  include:
    - stage: Dependencies
      script: nuget restore LuxaforLyncTool/LuxaforLyncTool.sln
    - script: nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  
  - stage: Build
    script: dotnet build ".\LuxaforLyncTool\LuxaforLyncTool_Light\LuxaforLyncTool_Light.csproj" -c Release
  - script: dotnet build ".\LuxaforLyncTool\LuxaforLyncTool_Lync\LuxaforLyncTool_Lync.csproj" -c Release
  - script: msbuild ".\LuxaforLyncTool\LuxaforLyncTool_Client\LuxaforLyncTool_Client.csproj" /t:Build /p:Configuration=Release
  - script: msbuild ".\LuxaforLyncTool\LuxaforLyncTool_Test\LuxaforLyncTool_Test.csproj" /t:Build /p:Configuration=Releas
  
  - stage: Tests
    script: mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./LuxaforLyncTool/LuxaforLyncTool_Test/bin/Release/LuxaforLyncTool_Test.dll
