language: csharp
dotnet: 2.0.0
solution: LuxaforLyncTool/LuxaforLyncTool.sln

install:
  # Restore NuGet packages
  - nuget restore LuxaforLyncTool/LuxaforLyncTool.sln
  # Install an xunit test runner
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
  
script:
  # Individually build the .netstandard projects
  - dotnet build ".\LuxaforLyncTool\LuxaforLyncTool_Light\LuxaforLyncTool_Light.csproj" -c Release
  - dotnet build ".\LuxaforLyncTool\LuxaforLyncTool_Lync\LuxaforLyncTool_Lync.csproj" -c Release
  
  # Build the WinForms project
  - msbuild ".\LuxaforLyncTool\LuxaforLyncTool_Client\LuxaforLyncTool_Client.csproj" /t:Build /p:Configuration=Release
  
  # Build the test project(s)
  - msbuild ".\LuxaforLyncTool\LuxaforLyncTool_Test\LuxaforLyncTool_Test.csproj" /t:Build /p:Configuration=Release
  
  # Run the unit tests
  - mono "./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe" ./LuxaforLyncTool/LuxaforLyncTool_Test/bin/Release/LuxaforLyncTool_Test.dll
  
  - ls
  - cd testrunner
  - ls
  - cd xunit.runners.1.9.2
  - ls
  - cd tools
  #- ls
  #- cd Release
  #- ls
