language: csharp
mono: none
dotnet: 2.0.0
solution: LuxaforLyncTool/LuxaforLyncTool.sln
script:
  - cd LuxaforLyncTool
  - dotnet restore
  - dotnet build \LuxaforLyncTool_Light\LuxaforLyncTool_Light.csproj -c Release
  - dotnet build \LuxaforLyncTool_Lync\LuxaforLyncTool_Lync.csproj -c Release
  #- dotnet build -c Release -f net461
