language: csharp
mono: none
#solution: LuxaforLyncTool/LuxaforLyncTool.sln

install:
  - msbuild /t:Restore LuxaforLyncTool/LuxaforLyncTool.sln
  
script:
  - msbuild /t:Build /p:Configuration=Release LuxaforLyncTool/LuxaforLyncTool.sln
