language: csharp
dotnet: 2.0.0
solution: LuxaforLyncTool/LuxaforLyncTool.sln
install:
  # Install an NUnit test runner
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  # Restore nuget packages
  - cd LuxaforLyncTool
  - dotnet restore
  
  # Individually build the .netstandard projects
  - cd LuxaforLyncTool_Light
  - dotnet build LuxaforLyncTool_Light.csproj -c Release
  
  - cd ..
  - cd LuxaforLyncTool_Lync
  - dotnet build LuxaforLyncTool_Lync.csproj -c Release
  
  # build the WinForms project
  - cd ..
  - cd LuxaforLyncTool_Client
  - msbuild LuxaforLyncTool_Client.csproj /t:Build /p:Configuration=Release
  
  # Run the unit tests
  - cd LuxaforLyncTool_Test
  - mono ../../testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe bin\Release\LuxaforLyncTool_Test.dll
